### ISSUE TITLE
Feature request. page:before-change on back button

### ISSUE THREAD

**Issue by woto** [rails/turbolinks#273]
Hi, sorry for bad English. I didn't find mailing list that's why my question here. Is there a plans to allow to prevent clicking back button as it were made with links (page:before-change)? It will be usefull in situations with plugins like "dirty form" or "are you sure" to prevent loosing partially filled forms during redirect.

**Comment by shadowed87** [comment]
Is it there any workaround for this? Really need to intercept the back button

**Comment by reed** [comment]
The popstate event can't be canceled.  And it makes sense why browsers implement it that way.  The user has explicitly told the browser they want to go back to the previous page.  A website shouldn't be able to prevent that from happening.  

I'm going to close this, for the reason I just described and also the fact that there's no apparent way to implement it.

**Comment by ardensol** [comment]
My workaround was adding to the history stack with turbolinks set to false: 

var url = 'fakeurl.com/url#step-1'
history.pushState({turbolinks: false, url: url}, '', url);

I then added a hash on the id link of my multi-step form where I navigated to

window.location.hash = 'step-2';

and set up a listener to fade the form in and out based on the hash change:

window.onhashchange = checkHashChange;

var checkHashChange = function() {
  doSomething();
}
