### ISSUE TITLE
document.addEventListener "page:load" doesn't act as $( window ).on "load", ()->

### ISSUE THREAD

**Issue by sgrosse** [rails/turbolinks#295]
Hey there,

in my current project I differentiate between stuff that runs at
"$( document ).ready" (as an example for DOMready) and some other stuff that runs on "window.onload". I'm doing that because I e.g. equalize some heights and adjust some styles in my layout according to current content. If there's some image in my content i need to use "window.onload" because it fires after everything is loaded. The problem is, that document.addEventListener "page:load" acts more like $( document ).ready than like window.onload. I just wonder if that is on purpose or if I'm missing something. As far as I unterstand the documentation, "page:change" is something like "$( document ).ready" and "page:load" should be more or less like "window.onload".

I don't know if I'm the only one with problems like this but I would strongly request this as a fix or feature.

Thanks in advance. ( And thanks by the way for this nice piece of software )

Stefan

**Comment by chrisjacob** [comment]
How about this? ... should work for first page load, new page load, and restoring a page from cache?

```javascript
    /*
     * Window.onload will be triggered on the first page load as normal, and then manually for Turbolinks pages.
     */
    window.loadEventsBound = false;
    $(document).on('page:change', function(){
        if(window.loadEventsBound) {
            // Assuming all JS and CSS is downloaded and processed on the first page load...
            // ...then when loading a new page via Turbolinks the only thing delaying Window.onload is Images.
            // So use: http://imagesloaded.desandro.com -- and JavaScript is all like "You images done yet or what?"
            imagesLoaded('body', function(){
                $(window).trigger('load');
            });
        }
    });
    $(window).on('load', function(){
        window.loadEventsBound = true;
        console.log('Window loaded');
    });
```

**Comment by Thibaut** [comment]
I don't think we should be delaying the `page:load` event until all images have loaded.

@chrisjacob's solution is a good work-around. Feel free to PR a new event that behaves like that if the code required to make it work isn't too long.
