### ISSUE TITLE
Make events attached to page:change fire if DOMContentLoaded has already passed?

### ISSUE THREAD

**Issue by sbull** [rails/turbolinks#306]
Hi there,

I'm upgrading to Turbolinks 2.0, and I also use jQuery. The update to page:change seems to make things easier, but I'm wondering if it could be tweaked at all to be more similar to jQuery's .ready() function. The big difference that I'm noticing is that .ready() fires the callback even if the DOMContentLoaded has already passed, whereas callbacks attached to page:change wait until the next page:change event to fire if the DOMContentLoaded event has already passed (and do not fire immediately on the already-loaded page).

I'm curious if the intent of the modification to page:change would be to provide a more straightforward replacement to .ready(). If so, it seems that there's still a difference, which may need to be addressed. If not, then perhaps another event could be introduced to bridge the gap between .ready() and page:change?

For the curious, here's what I'm planning for a workaround:
```
$(function(){
  myCallback(); // Fire callback on DOMContentLoaded, or now if it has already passed.
  $(document).on('page:change', myCallback); // Register it for the next page:change event.
});
```

**Comment by Thibaut** [comment]
This may be useful, but also quite complex to implement. Feel free to open a PR if you still want it.
