### ISSUE TITLE
No scroll position reset when asset change causes reload

### ISSUE THREAD

**Issue by christianlerke** [rails/turbolinks#320]
The scroll position is not reset to the top when the page is reloaded because of an asset change.
Could be fixed within the `validateResponse` function by resetting the scroll position before reloading the page:
```
window.scrollTo(0,0);
window.location.reload();
```

**Comment by barrkel** [comment]
Seconding this. It's especially tedious on mobile, where you may have a long way to scroll back to the top of the page, and no handy Home button to get there faster.

**Comment by Thibaut** [comment]
Why should the reload scroll to the top? As a user I think it makes more sense to go back to the same scroll position. Most of the time an asset change doesn't radically change the site.
