### ISSUE TITLE
html5 canvas is not working in iOS Safari

### ISSUE THREAD

**Issue by goooseman** [rails/turbolinks#326]
I'm working on my wife's pet project and I use turbolinks. I have really believed, that I coped with all turbolinks related issues, but when I began to test site on iPad I found really strange bug:
**html5 canvas is not working on iOS Safari  when using turbolinks.**  
  
To repeat this bug you can go to [my site](http://aliya-soap.ru/) on an iPad (or iPhone or iPod) and press 'Конструктор мыла' link in the navbar (the first one in the navbar). On the middle of the page there is a canvas, but it isn't get loaded. If you refresh the page, everything will work fine.  
  
On Android and on any desktop browser (even Safari on Mac OS) everything is fine.

The problem is that I can't debug on iPad, so I can't debug the problem.  
  
The question is how to deal with this bug.  

And as a temporary solution, **how can I disable turbolinks for only iOS devices?**

Looking forward for your answer,
Alexander.

P.S. And yes, there is [this issue on the stackoverflow](http://stackoverflow.com/questions/19469287/rails-4-turbolinks-cause-html-canvas-to-disappear-on-ipad), but the only suggestion is to disable turbolinks at all.

**UPD** I have created a demo. Go to [this page](http://murmuring-shore-5170.herokuapp.com/) from an iOS device and push 'Canvas' link. The Canvas doesn't get loaded.  Refresh and see the diffrence.

**Comment by Thibaut** [comment]
Feel free to re-open if this is still an issue.
