### ISSUE TITLE
Inline background-images are not loaded

### ISSUE THREAD

**Issue by inspire22** [rails/turbolinks#370]
This seems to have been a problem for awhile, as I see workarounds for it in various places ( http://carlosbecker.com/posts/turbolinks/ ) 

When navigating via turbolinks in google chrome (not sure about other browsers), inline elements with style="background-image:url(blah)" do not show the background images.  Using javascript to set the style to what it currently shows does fix the problem, like his solution from the above page:

		var reloadImages = function() {
		  var styles, style, url, _i, _len, _el;
		  styles = Array.prototype.slice.call(document.body.querySelectorAll('[style]'));
		  for (_i = 0, _len = styles.length; _i < _len; _i++) {
		    _el = styles[_i]
		    style = _el.getAttribute('style');
		    if (!(style.indexOf('url(') > -1)) {
		      continue;
		    }
		    url = style.match(/url\((.*)\)/)[1];
		    _el.style.backgroundImage = 'url(' + url + ')';
		  }
		}
		$(document).on('page:change', function() {
		  reloadImages();
		});

I'm kinda surprised no one else has noted this here, as it seems like a pretty big issue...

It's possible it only happens when using protocol-relative urls (which is necessary if your site can be viewed with ssl or non-ssl).

    <a class="spotlight_image_box" href="/" style="background-image: url(//ap-pics.gotpoem.com/ap-pics/item/11436/849.jpg?happinessjpg)">test</a>

**Comment by Thibaut** [comment]
@inspire22 @dmastylo @hakunin is this still happening with turbolinks master?

I tried to reproduce with both protocol-relative and relative URLs but couldn't.

**Comment by hakunin** [comment]
no longer using turbolinks in my app

**Comment by Thibaut** [comment]
Without repro steps I can't fix this. Feel free to link to a demo and I'll re-open / try to fix it.
