### ISSUE TITLE
Appending Items using JS.

### ISSUE THREAD

**Issue by michaeltrilford** [rails/turbolinks#402]
As noted in another Issue, items are added to the DOM when you navigate around the site when they are added via JS.

I'm trying to understand why this happens? Is this why the "data-no-turbolink" exists? Should we put this on our navigation items? If so, I can't see the reason for Turbolinks?

Yours sincerely,
Turbolink noob.

![screen shot 2014-09-15 at 12 27 30 pm](https://cloud.githubusercontent.com/assets/2483515/4266763/c1754800-3c86-11e4-80ab-6bf7bf52bc0a.png)

**Comment by Thibaut** [comment]
@michaeltrilford could you point to a simple HTML page where we can reproduce the problem?
