### ISSUE TITLE
SVG 'use' with External Source not working

### ISSUE THREAD

**Issue by JosepMartins** [rails/turbolinks#424]
Hi, 

I'm using  <use> tag to reference SVG from an external file, because that means that file can be cached by the browser. The SVG 'use' with [External Source](http://css-tricks.com/svg-use-external-source/) don't work with Turbolinks but when i define the shapes inside de page it works fine. 

Is there a way to make external SVG links work with Turbolinks?

Thanks!

**Comment by Thibaut** [comment]
Could you point to a simple HTML page where we can reproduce the problem?
