### ISSUE TITLE
Warning: cloneNode() 

### ISSUE THREAD

**Issue by MichaelRoshen** [rails/turbolinks#432]
turbolinks 2.5.2

rails new test_rails4_turbolinks
cd test_rails4_turbolinks
rails g scaffold User name:string age:integer
rake db:migrate

rails s
then vist http://localhost:3000/users , and  click button New User, see the browser‘s console 
it warns: document.documentElement.cloneNode();

it works on turbolinks version 2.3.0

**Comment by reed** [comment]
What browser do you see the warning in?

**Comment by Thibaut** [comment]
@MichaelRoshen ping (@reed's question)

**Comment by Thibaut** [comment]
Can't reproduce in Firefox/Chrome/Safari/IE10.
