### ISSUE TITLE
autofocus on page-load should select any existing text

### ISSUE THREAD

**Issue by mintcore** [rails/turbolinks#450]
Since #365 turbolinks automatically focuses inputs with the autofocus attribute. 
I think it would be more correct that any existing text in the focused input were to be selected on the focus event

**Comment by reed** [comment]
Safari already does this, both on normal page loads and on Turbolinks page loads when `.focus()` is called.  Firefox and Chrome don't.  In general, we do everything we can to maintain native browser behavior, only actively fixing things that Turbolinks has broken (like setting the focus on elements with the autofocus attribute).  It isn't the role of Turbolinks to fix browser discrepancies.  The Safari behavior shows that if a browser wants autofocused elements to have existing text selected, Turbolinks isn't preventing it.  If you or anyone else ever find a case now or in the future where that isn't true, then we'll take action.  Just reopen the PR if you do.
