### ISSUE TITLE
Back Button Not Working - Turbolinks 2.5.3 and Rails 4.0.13

### ISSUE THREAD

**Issue by slatem** [rails/turbolinks#453]
Back button isn't working for me on Turbolinks 2.5.3 and Rails 4.0.13 on any browser.

**Comment by slatem** [comment]
Actually it appears that I was wrong. The back button isn't working at all in any browser on latest Turbolinks 2.5.3 and Rails 4.0.13

**Comment by slatem** [comment]
Switching back to 1.3.1 fixes it.

**Comment by slatem** [comment]
It breaks right at the 2.0.0 version so must be something there that's incompatible with Rails 4.0.13

**Comment by alexJunger** [comment]
Having the same issue - and downgrading to 1.3.1 doesn't help either.

**Comment by slatem** [comment]
Upgraded to Rails 4.1.9 and Turbolinks 2.5.3 and back button is still broken. Downgrading to 1.3.1 fixes it again.

**Comment by reed** [comment]
The back button works fine for me for Rails 3.2, 4.0.13, 4.1, and 4.2.  Considering that neither Turbolinks 2 nor Rails 4.0 are new releases, if there was an issue we would've heard about it a lot sooner than now, and from a lot more people.  There must be something in your code that's causing the problem, or the problem pertains to a specific scenario that you're not providing any details about.

**Comment by Thibaut** [comment]
@slatem @alexJunger I'm happy to look into this but could you point to a simple website or repo where I can reproduce? Also could you try turbolinks master? (there are many unreleased changes that may have fixed this)

**Comment by Thibaut** [comment]
Without repro steps or an example app we can't fix this. Feel free to provide more info and we'll reopen / look into it.

**Comment by alexJunger** [comment]
I'm sorry @Thibaut, I can't disclose the project where this occured and I don't have time right now to re-create it as a *clean* app. Guess that's okay since it doesn't seem to happen to many others, however I might provide some more info at some point.
