### ISSUE TITLE
Issues with submitting forms

### ISSUE THREAD

**Issue by MGotink** [rails/turbolinks#458]
In chrome 40 (and safari 8.0.3 in some cases) the history is broken when you submit a form and quickly click back twice. The url points to the page before the form but the page displayed is the form itself:
![screen shot 2015-02-13 at 19 32 28](https://cloud.githubusercontent.com/assets/3357803/6192948/1bdcbbc8-b3b7-11e4-8ebf-1233adc773ea.png)
With chrome I can reproduce this on both the test server and a rails application.
With safari I can only reproduce this on a rails application, not on the test server.
Also, after you submit the form and go back safari could display the initial contents for the form, maybe related to #332. I can only reproduce this on the test server, not on a rails server, maybe due to difference in caching/timing?

The invalid page being displayed can be fixed by reverting e69bead, that's no problem anymore for chrome, but now safari will display the initial form contents (as described above) on both the rails and test server. I've tried to find a more robust solution, but no luck so far.

Demo code and reverted mentioned commit can be found here:
https://github.com/MGotink/turbolinks/tree/history_after_post

**Comment by Thibaut** [comment]
Do you have a demo app I can use to reproduce?

**Comment by MGotink** [comment]
The link at the end of my previous message points to some demo code.
