### ISSUE TITLE
Access to the ProgressBar API

### ISSUE THREAD

**Issue by haggen** [rails/turbolinks#462]
I'd like, in some circumstances, to start/stop the progress bar manually. Could the ProgressBar API be exposed for such cases ?

For example (not actual working code):
```js
Turbolinks.ProgressBar.start();
```

**Comment by javan** [comment]
I'm open to that. Can you explain how you'd use it?

**Comment by haggen** [comment]
Sure. There 2 cases. 1) I'm using a remote link to change something via AJAX and then calling Turbolinks.visit to reload the page, I'd like to display the progress on the AJAX call. 2) I'm making my forms to work via AJAX and change the page also using Turbolinks.visit.

**Comment by haggen** [comment]
Thanks guys, you're awesome!
