### ISSUE TITLE
Javascript called twice when server redirect

### ISSUE THREAD

**Issue by arthurtalkgoal** [rails/turbolinks#464]
My project installed jquery.turbolinks and turbolinks.

The wysihtml5 editor is triggered twice.

Here is my js.coffee codes
```
//= require bootstrap-wysihtml5
//= require bootstrap-wysihtml5/locales/zh-TW
//= require bootstrap-wysihtml5/locales/zh-CN
...
//= require_self

$('textarea').each ->
  $(this).wysihtml5()
$(document).ready ->
  ...  
```

My server redirect user to the ***final product*** view from the ***first turotial*** controller as normal html call. It works fine without turbolinks. Otherwise, the html5  editor will be triggered twice. Seems the following redirection created the problem; from firebug - 

```

GET http://myhost.com/wireframe/tutorials/description/dTrcN  302 Found  308ms  turbolink.js...?body=1（132 row）
GET http://myhost.com/shop/admin/products/test-2-6e9281b8-0647-48ef-a967-333373c1d71d/edit 	
200 OK

```

![twice](https://cloud.githubusercontent.com/assets/7088330/6355912/a7f635c2-bc94-11e4-8488-3fbca14ed005.jpg)

**Comment by reed** [comment]
Where in the page do you include your site's javascript?

**Comment by arthurtalkgoal** [comment]
Hi @reed,

thanks for your help. I figure out it is the wyishtml5 set up need the follow script with turbolinks:

```
$(document).on('page:load', function(){
  window['rangy'].initialized = false
})
```

**Comment by reed** [comment]
Glad you got it working.
