### ISSUE TITLE
Add a cache busting param for IE

### ISSUE THREAD

**Issue by davydotcom** [rails/turbolinks#467]
IE is dumb, so now that turbolinks works in IE we have to do some small thing. We need to send a cache busting param otherwise its too aggressive on its caching of pages..

Do like jquery cache:false does and pass a param `&_1425044146793` i.e.

```coffee
url = "#{url}&_#{new Date().time}"
```

**Comment by nowhereman** [comment]
@davydotcom Can you tell us which versions of IE have this issue, please ?

**Comment by davydotcom** [comment]
It's been around a long time but I'm seeing it on IE11

**Comment by nowhereman** [comment]
See https://github.com/defunkt/jquery-pjax/pull/496https://github.com/defunkt/jquery-pjax/pull/496

**Comment by mislav** [comment]
Note that IE indeed has a history of aggressively caching HTTP resources, but it *does* respect cache-controlling response headers if you set them from the application.

**Comment by reed** [comment]
@davydotcom Would you recommend adding the param across the board or specifically targeting IE?
