### ISSUE TITLE
Don't necessarily clone nodes, but move them, when using `data-turbolinks-permanent`

### ISSUE THREAD

**Issue by jtomaszewski** [rails/turbolinks#477]
Currently, if I use `data-turbolinks-permanent`, [nodes are being cloned into a new document](https://github.com/rails/turbolinks/blob/05436161a8208e6e8e09e9e3f3eb4a1854056f40/lib/assets/javascripts/turbolinks.js.coffee#L175-L176). 

This is not really the behaviour I need, because:
- it removes event bindings
- f.e. if this element has some `iframe` elements in it, they will be loaded again

If we would just move the node from one document to the new one, we could avoid it.
What do you think about it and how we could implement it?

P.S. My usage example: I want to create a "music player widget" that is fixed to the whole webpage and shouldn't be reloaded between requests. It has some event bindings (f.e. `$(".play-button").on("click", startPlayer)`). Also it can contain f.e. a youtube iframe in itself - and obviously I don't want the iframe contents to be reloaded, so the video can keep playing.

**Comment by Thibaut** [comment]
This issue came up in https://github.com/rails/turbolinks/pull/472/files#r25563876
I'll look into it today or tomorrow.
