### ISSUE TITLE
Turbolinks send ajax many times when click back button on a browser

### ISSUE THREAD

**Issue by shellfly** [rails/turbolinks#490]
use Rails 4.2 and turbolinks 2.5.3

**Comment by shellfly** [comment]
use Rails 4.2 and turbolinks 2.5.3

**Comment by Thibaut** [comment]
Could you create an example app where we can replicate the problem?

**Comment by shellfly** [comment]
I just use it on my first rails project: http://wanshiu.com/

You can replicate this issue by clicking some nav bar buttons and hit browser's back button

**Comment by Thibaut** [comment]
This is happening because you put your `<script [...] data-turbolinks-track="true">` in the `<body>`, so they (including Turbolinks) get re-evaluated on every page load. Move them to the `<head>` and everything will work normally.

**Comment by shellfly** [comment]
Problem solved. Thanks for your help!
