### ISSUE TITLE
turbo-react

### ISSUE THREAD

**Issue by tmlayton** [rails/turbolinks#491]
In #448 @ssorallen mentioned:

> I added React as an experiment to have finger-grained automatic mutations than documentElement.replaceChild to enable things like CSS transitions.

I'm interested in continuing the discussion. Is it possible to move beyond an experiment and, if so, what are the considerations?

/cc @qq99

**Comment by qq99** [comment]
https://github.com/ssorallen/turbo-react

**Comment by qq99** [comment]
The code linked does `global.document.documentElement.replaceChild = Reactize.applyDiff;`

It may be nice if Turbolinks supplied a `Turbolinks.replaceNode(parent, child)` in the public API so that one could override this more cleanly

**Comment by tmlayton** [comment]
Sorry didn't realize there was a turbo-react repo. Closing and moving this

**Comment by qq99** [comment]
I think this may still be a good place to discuss it wrt interplay between the 2 libraries.  I'm not sure that Turbolinks should ever include turbo-react, but if we can discuss here how to make the integration between the two smoother, that'd be good

**Comment by qq99** [comment]
The other missing part, I feel, would be this:

```coffee
    } catch(e) {
      // If any problem occurs when updating content, send the browser to a full
      // load of what should have been the next page. Reactize should not
      // prevent navigation if there's an exception.
      if (nextDocument !== undefined && nextDocument.URL !== undefined) {
        global.location.href = nextDocument.URL;
      }
```

instead of doing this, it would be better to call the original `Turbolinks.replaceNode`
