### ISSUE TITLE
Is there any solution to make Google adsense work with turbolinks?

### ISSUE THREAD

**Issue by mydemos** [rails/turbolinks#501]
I'm using turbolinks in my rails 4 Application but google adsense is not appearing, so I'm wondering if there is any solution to this issue I have tried this solution https://github.com/rails/turbolinks/issues/151 but it don't seem to be working

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
