### ISSUE TITLE
Enable Progressbar

### ISSUE THREAD

**Issue by cars10** [rails/turbolinks#506]
Hey folks, as of the current Version of turbolinks (2.5.3) i cannot enable the progressbar with the command from the wiki.

Turbolinks.ProgressBar.enable();

gives me a js error. Using 

Turbolinks.enableProgressBar()

 on the other hand works without problems. is this an error in the wiki?

**Comment by confact** [comment]
Will it work if you add this to your require?
```//= require nprogress-turbolinks```

**Comment by cars10** [comment]
This require throws an error - "couldn't find file 'nprogress-turbolinks' with type 'application/javascript'"

**Comment by reed** [comment]
The master branch on github is currently at version 3.0.0, and the progress bar API changed from what it was in version 2.  If you want to read the readme for version 2.5.3, go [here](https://github.com/rails/turbolinks/tree/v.2.5.3).

**Comment by cars10** [comment]
that is. thanks! a hint for that might be nice in the wiki.
