### ISSUE TITLE
Turbolinks doesn't run scripts on `back`

### ISSUE THREAD

**Issue by kevinhughes27** [rails/turbolinks#507]
Looks like Turbolinks doesn't re-run scripts in the body when the back button is pressed:
https://github.com/rails/turbolinks/blob/master/lib/assets/javascripts/turbolinks.js.coffee#L94 - is there a specific reason for this? Could we change this or make it configurable?

@Thibaut

**Comment by Thibaut** [comment]
@reed mentioned in #478:

> Because those scripts have already been executed for that page. And since the transition cache uses `fetchHistory`, the scripts would run then too. 

I think both use-cases are legit and we should make this opt-in. Maybe with `data-turbolinks-eval=true`?
