### ISSUE TITLE
redirect_to and render not working

### ISSUE THREAD

**Issue by mbajur** [rails/turbolinks#512]
Hello!
I've recently found that, from some time, turbolinks supports partial replacing from controller method and i'm super excited about that. However, after few attempts on making it work in my app, i'm still not table to use it. My use case is quite simple - i have a form with two fields which sends a remote POST request to `/users/invite` path. After successful submission, i want to reload that whole form. It has an id set to `#place_users` and `remote: true`.

My `invite_user` action looks like that:

```
def invite_user
  @result  = PlacesService::InviteUser.new(@place, invitation_params)
  @result.call

  redirect_to users_place_path(@place), turbolinks: true
```

And form:

```
= form_tag invite_user_place_path, data: { remote: true }, id: 'place_users' do
  input type="text"
  input type="submit"
```

After sending that form, there are no exceptions nor anything else and there are two requests visible in `Network` tab of chrome's OI: `POST /place/invite_user` and `GET /place/users` (the second one is the page with a form) but nothing is reloaded (for simplicity's sake i'm not trying to reload a single div but whole body).

I have completely no idea how can i debug turbolinks and to exactly know what are they doing but interesting thing is that i'm able to run, for example, `Turbolinks.visit('/place/users', {change: 'place_users'})` in javascript console and it works as it should. It seems that just runnig turbolinks stuff from controller actions is broken somewhere. I don't know if that's a clue but i'm trying to use it **in engine**.

Have you any idea on what am i possibly doing wrong in here or how can i debug that?
Thanks in advance

**Comment by Thibaut** [comment]
Have you tried:

```ruby
redirect_to users_place_path(@place), change: 'place_users'
```

**Comment by mbajur** [comment]
Yeah, but it was not working neither.

**Comment by Thibaut** [comment]
What's the response body of the `POST /place/invite_user` request?

**Comment by mbajur** [comment]
There is no body, just a 302 redirect to `users_place_path`

**Comment by Thibaut** [comment]
Are you using the latest master? What does `Turbolinks::VERSION` give you in the rails console?

>  I don't know if that's a clue but i'm trying to use it in engine.

What do you mean?

**Comment by mbajur** [comment]
```
> Turbolinks::VERSION
 => "2.5.3"
```

I mean that i have a rails engine and i'm trying to use the code above in it, not in the root app.

**Comment by Thibaut** [comment]
You're not using Turbolinks master. Add this to your `Gemfile`:
```
gem 'turbolinks', github: 'rails/turbolinks', branch: 'master'
```

**Comment by Thibaut** [comment]
No problem ;)

**Comment by galulex** [comment]
@Thibaut I have `3.0.0` version of turbolinks and it does not work.
When i run `render :show, keep: :foo, flush: true` i should get an error. But it just renders the view

**Comment by Thibaut** [comment]
@galulex what do you mean you "should get an errror"? If you do `render :show, keep: :foo, flush: true`, the `flush` option will be ignored since `keep` takes precedence over it. However, you'll only get a `Turbolinks.replace` response on XHR requests (e.g. `jQuery.ajax`, but not `Turbolinks.visit`).

**Comment by galulex** [comment]
@Thibaut thanks for your response. i will check

**Comment by galulex** [comment]
@Thibaut I was talking about [this line](https://github.com/rails/turbolinks/blob/master/lib/turbolinks/redirection.rb#L40). Also I have checked with XHR request and get the same results. I always get the `html` but it should be wrapped with `Turbolinks`

**Comment by Thibaut** [comment]
@galulex Right. Sorry I forgot we had that. Is `request.xhr?` true before the call to `render`?

**Comment by galulex** [comment]
@Thibaut `request.xhr?` returns 0 when i click on remote link, in all other cases it is `nil`.

**Comment by Thibaut** [comment]
@galulex the Turbolinks `render` / `redirect_to` options only apply to XHR requests (remote links). You should get an exception in that case (only).

**Comment by galulex** [comment]
Gotcha! the problem was with [remotipart gem](https://github.com/JangoSteve/remotipart) it overwrites the `render` method. Will create an issue there. @Thibaut thanks you for your responses.
