### ISSUE TITLE
Scripts running out of order

### ISSUE THREAD

**Issue by sidot3291** [rails/turbolinks#513]
See this question on StackOverflow:
http://stackoverflow.com/questions/29785887/scripts-loading-out-of-order-in-chrome

I know you can use a loader like javascript-loaders to define the order that script tags are run.  Potentially the same can be done here.

For now I'm moving the external script tag to my head and including it on every page of my app, so it should be guaranteed to be loaded before I reach the page-specific code.

**Comment by Thibaut** [comment]
Due to browser limitations, we can't fix this without implementing a JavaScript loader within Turbolinks.
See https://github.com/defunkt/jquery-pjax/issues/331 for more info.

Closing as `#wontfix`. If a solution surfaces feel free to comment and we'll re-open.
