### ISSUE TITLE
Turbolinks header in requests

### ISSUE THREAD

**Issue by riccardoa** [rails/turbolinks#515]
Hi,
I wonder if turbolinks has a specific header (like request.headers['X-PJAX'] for PJAX)...
This will be very useful for the new partial feature in turbolinks3, because I wonder how I can manage the browser that doesn't support pushState and in my controller I have only: ```render '_comment', change: :comments``` like reply.
So, how I should manage if a browser doesn't support pushState ? with a simple header, will be very easy.

What is your suggestions ? how do you manage it ?

Thanks.

PS: I've googled for looking if turbolinks has a specific header, but I didn't find anything.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by riccardoa** [comment]
@rafaelfranca sorry about it, I wasn't sure if was best here or stackoverflow, but my main concern was:
why don't implement the request header ? (so was a feature request/discussion)
btw sorry again, I really appreciate the work that you guys are doing with rails and turbolinks!

**Comment by rafaelfranca** [comment]
No problem. BTW, this message is semi-automatic. We usually don't take feature requests at our issues trackers.

But I think I can answer that question. If you want a header just to manage browsers that not support pushState is not better to just use a polyfill? https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills#html5-history-api-pushstate-replacestate-popstate

**Comment by riccardoa** [comment]
@rafaelfranca I will try it! thank you and sorry again!

**Comment by Thibaut** [comment]
@riccardoa you should be rendering the full index view, not a partial:

```ruby
render :index, change: :comments
```

Turbolinks will only replace the response with `Turbolinks.replace([...], change: ['comments'])` when the request is XHR, so if you make your JavaScript perform an XHR only for browsers that support `pushState` (Turbolinks does that for links already, forms are up to you), it will all work (non-pushState browsers will get a normal HTML response, pushState browsers will get a Turbolinks response following an XHR).

**Comment by riccardoa** [comment]
@Thibaut Why I should reply with a full index view, when I don't need it ? the problem is that it's different the response time/size.

If I reply only with a partial it's only 20ms vs 100ms for the full index view...if wasn't for the problem in old browser, this solution works very well and it's competitive with backbone or other mvc js frameworks.

It's like when I do:
```redirect_to @post, change: [:comments, :super_test]```
It reply to me with a full page html(that is a lot more big than a simple partial)

**Comment by dhh** [comment]
If you want to render only partials, then pjax is probably a better fit for your use case.

**Comment by Thibaut** [comment]
@riccardoa If you use Russian-doll caching then rendering the full index view is not a problem. This is the recommended way of using Turbolinks.

The size of the response doesn't matter — with gzip the difference is negligible.

**Comment by riccardoa** [comment]
@dhh yes but for example I need this specific thing only for 1 page...for the rest of all website turbolinks does great.
We don't always need best performances, but it's useful have this option when you need it.

**Comment by riccardoa** [comment]
Just a question:
Why don't give the opportunity to people to render page/html conditionally  ? it's only need a custom header(like pjax)

**Comment by Thibaut** [comment]
> Why don't give the opportunity to people to render page/html conditionally ?

If you use `jquery-ujs`, you can already do this:

```
render :index, change: :comments, layout: (request.xhr? ? nil : 'application')
```

However, I just realized Turbolinks doesn't send `X-Requested-With: XMLHttpRequest` when it fetches a page, so `request.xhr?` won't be `true`. @dhh any reason why that's not the case? Ok if I make the change?

**Comment by dhh** [comment]
That wouldn't work for us. We use xhr when we are doing other Ajax requests. I'd suggest doing a manual Ajax request for that 1 request in your app when you want to render a partial.

**Comment by riccardoa** [comment]
Guys, but why doesn't implement a simple and specific header for every turbolinks request ? honestly I think it worth it...
Turbolinks is more powerful than jquery-pjax right now...
example:
- Don't need jquery specifically
- It can change multiple blocks at the time(thing that with jquery-pjax you can't do easily)
```request.xhr?``` it very generic and could be any ajax request, so myabe people that doesn't know code, could be have some problems at the begin to figure out where is simple ajax or where works with turbolinks.

EDIT: Ok just read the @dhh reply! honestly yes it's not a problem of my application specifically(also because I can fork turbolinks and add a custom header), but I wanted listen your opinions.

**Comment by riccardoa** [comment]
Ok just a update:
For now I'll use turbograft where with only 2 line of codes I've added a custom header to normal and form requests...
The problem with turbolinks is that is easy add the custom header for requests, but not for form request(where Turbograft has a custom class called Turbograft.Remote)

I really hope that this will be introduced in turbolinks too(not specifically the Remote class, but that for every request/submitted form there is a custom header)...now that turbolinks supports for partials, user should be able to manage when the request is done by Turbolinks or not).

The Turbolinks concept is really good now that it supports for partials too(but without a custom header, it's a bit useless IMHO) and I'm dropping my MVC JS framework :) so thank you @dhh and team!

**Comment by Thibaut** [comment]
@riccardoa with regards to custom headers, Turbograft works exactly the same way as Turbolinks + `jquery-ujs`.

- on custom XHRs (`Turbograft.Remote` vs. `$.ajax`) and remote forms, a custom header is sent (`X-Requested-With: XMLHttpRequest`), which you can check with `request.xhr?` in your controller.
- on page visits, there is no custom header. You can/should re-render the entire page all the time.

**Comment by riccardoa** [comment]
@Thibaut Yes I know but was easy add it(I've customized the gem), btw I will try to do some other test.
I've some doubt that I can check ```request.xhr?``` because:
If a user use my form with ```remote: true```, I think that I still got the request.xhr? true, also if the request isn't done by turbolinks(because user is using IE8 and doesn't support pushState)

I wonder why you say: ```You can/should re-render the entire page all the time.``` so what is it the useful stuff about partials ? just that I can have permanent nodes ?

**Comment by Thibaut** [comment]
> The problem with turbolinks is that is easy add the custom header for requests, but not for form request(where Turbograft has a custom class called Turbograft.Remote)

With Turbolinks, which headers you send on XHR / form requests is entirely up to you, since Turbolinks doesn't provide this functionality.

If you use jQuery, just do:
```javascript
.ajaxSetup({
    headers: { 'x-foo': 'bar' }
});
```

Both Turbolinks and Turbograft will not let you add custom headers to page-visit requests. 

> so what is it the useful stuff about partials ?

To be able to refresh parts of a page without losing state (e.g. a search form that reloads as-you-type).

> If a user use my form with remote: true, I think that I still got the request.xhr? true, also if the request isn't done by turbolinks(because user is using IE8 and doesn't support pushState)

Now this is a problem. I believe `render :foo, change: 'bar'` + `jquery-ujs` is broken on browsers that don't support `pushState`, because we don't have a fallback for `Turbolinks.replace` :/

**Comment by riccardoa** [comment]
@Thibaut right now I feel like a complete idiot...I don't have thought about something so easy like ajaxSetup...sorry for the time lost!
Honestly my problem now is fixed! maybe we should think about a fallback for Turbolinks.replace for all the community/people that want use tubolinks.

Thanks you so much to all people of this discussion and the team of turbolinks.

**Comment by Thibaut** [comment]
@riccardoa :+1: 

`Turbolinks.replace` should actually work in all browsers that support `querySelectorAll` (including non-pushState browsers like IE 9). I'll investigate in the coming weeks.
