### ISSUE TITLE
Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by ginolon** [rails/turbolinks#520]
How to use this new Turbolinks 3.0 (branch: 'master') with Rails 4.2?

I'm trying and I got from Chrome this error:

` Uncaught SyntaxError: Unexpected token : `

If I use partial replacement like this:

`<%= link_to "Something", root_path %>`

and then in the same page:

`<script>
Turbolinks.visit(url, { change: 'areaDiv' });
</script>`

The page is reloaded entirely and I got that error. How to do?

**Comment by Thibaut** [comment]
This doesn't give us enough information to replicate the issue. Could you put an example app on GitHub/Heroku?

**Comment by ginolon** [comment]
I can't post on Heroku. I have a standard Rails app 4.2.
I added in Gemfile the turbolinks gem from tighub branch master and now I use in my views index.html.erb a link_to from sidebar to update div "areaDiv".

The link_to is on the same page. It'a a link with params that filter the query from controller.

I repeat, all too standard.

But it just doesn't work.

The page just reload entire, like normal link.

Question: I have to put thi in index.html.erb:

` <%= link_to "Something", root_path({category: category.name, game: game}) %>`

and then I have to write this below the "link_to"?

`<script> Turbolinks.visit(url, { change: 'areaDiv' }); </script>`

I don't understand how to do. Is there an example on a standard app?

I need the transformation in views, not in controller. Because I have a standard menu just with some category filter.

How to do partial replacement in this way?

I think turbolinks partial replacement is for not use heavy javascript framework like angular. Because simply partial replacement is not too much complicated to use it with Angular. I'm wrong?

**Comment by Thibaut** [comment]
Did you include `turbolinks.coffee` in your javascript bundle?

> and then I have to write this below the "link_to"?

No. You need to run that javascript code dynamically, not put it in a `<script>` tag.

This doesn't sound like a Turbolinks issue. Until you have an example code / repro steps, please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you.

**Comment by ginolon** [comment]
Can you post an example for learn to me how to: "run that javascript code dynamically, not put it in a <script> tag."???

**Comment by Thibaut** [comment]
@ginolon a quick Google search for "javascript tutorial" or "turbolinks tutorial" will give you plenty of examples. I don't have time to help you beyond issues directly caused by Turbolinks, sorry.

**Comment by ginolon** [comment]
I'm usign onclick: in "link_to". I'm wrong?
