### ISSUE TITLE
"undefined" in my windows's title when I use Turbolinks 3.0.

### ISSUE THREAD

**Issue by ginolon** [rails/turbolinks#525]
I have Rails 4.2.1 standard.

In Gemfile I added: 

`gem 'turbolinks', :github => 'rails/turbolinks', :branch => 'master'`

Now in one controller I have:

```
  def ok_category
      render plain: "Ok", change: 'categoriesdiv'
  end
```

or maybe this:

```
  def red_category
      redirect_to "http://www.google.com", change: 'categoriesdiv'
  end
```

or another like this:

```
  def red_category
      render partial: 'category_choose', change: 'categoriesdiv'
  end
```

also if I add the `, turbolinks: true` at the end of each line, NOTHING!

My chrome window's title is changing in a laconic "**undefined**", but if I use the Chrome developer tool it says to me in "Network" tab that the request to the server is complete with "**GET**" method, "**304**" status, "**Text/Javascript**" type, all without errors.

In the **application.html.erb** I have:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Hello!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<div id="test"><%= Time.now.to_s %></div>
<div id="links"><%= link_to "Testmylink", ok_category_path(1), remote:true %></div>

<%= yield %>

<div id="categoriesdiv" data-turbolinks-temporary>Yes yes!</div>
<footer class="footer">
  <p class="text-center">Hello!</p>
</footer>
</div>
</body></html>
```

What is wrong with me?

**Comment by Thibaut** [comment]
Fixed this morning: 7bb5fa74b71b5b1ce83823f78a0c3a750b7d1032
