### ISSUE TITLE
"Security warning: an embedded <script> tag on another site requested protected JavaScript. If you know what you're doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding."

### ISSUE THREAD

**Issue by ginolon** [rails/turbolinks#527]
This error makes me crazy:

**routes.rb**

```ruby
get 'books/category/:category', to: 'books#chosen_category', as: :chosen_category
```

**books_controller.rb**

```ruby
def index
  #some codes for retrieve params[:category] and params[:tag]
  @books = Book.all
  @categories = Category.all
end

def chosen_category
  redirect_to books_path({category: params[:category], tag: params[:tag]}), turbolinks: true, change: 'categorydiv'
end
```

**views**
```ruby
<%= link_to "Something", controller: "books", action: "chosen_category", category: category.name, tag: tag, remote: true %>
```

and everything works good.

But when I try to navigate with browser (or with some old links) to something like this: *"books/category/FooBar"* it shows this error:

**Security warning: an embedded `<script>` tag on another site requested protected JavaScript. If you know what you're doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding.**

Why?

**Comment by Thibaut** [comment]
Remove `, turbolinks: true`. The option's primary purpose is to turn off Turbolinks responses in certain actions. Here you're forcing the response to be `Turbolinks.visit(...)` for all types of requests (not just XHRs / `remote: true`, which is the default), which means if you enter that URL in the address bar you'll see the JS response instead of being redirected.

**Comment by ginolon** [comment]
Ok, but if i remove `, turbolinks: true` Chrome says me in the "Network" tab that the queste is well completed and everything ok, but on my page nothing change.

With `, turbolinks: true` it works, but not with navigation with old link.

Why this?

**Comment by ginolon** [comment]
Or mayb in the controller:

```ruby
def chosen_category
  redirect_to books_path({category: params[:category], tag: params[:tag]}), turbolinks: true, change: 'categorydiv'
end
```

I have to check if the request is by remote: true or by address bar direct? It's a good way?

**Comment by Thibaut** [comment]
Try again without `turbolinks: true` ;)

**Comment by ginolon** [comment]
Thanks. Now it works. I'm so proud of being a tester for your beautiful job!

**Comment by ginolon** [comment]
Is there a way to not reload all queries in controller if I just want to "replace" with this new Turbolinks 3.0 just one part of the page and so just one part of the controller query?

Like unobtrusive way of partial render in ajax...
