### ISSUE TITLE
Eternal loading with "data-turbolinks-temporary"

### ISSUE THREAD

**Issue by ginolon** [rails/turbolinks#529]
The configuration is the same of my previous issue here:

https://github.com/rails/turbolinks/issues/525

when I add above `<%= yield %>`

a div like this:

```ruby
<div class="flashDiv" data-turbolinks-temporary><%= flash_messages %></div>
```

with

`data-turbolinks-temporary`

my application freezes on eternal loading (the blue bar in the top of page is freezed and in console everything is frozen.

**Comment by Thibaut** [comment]
Are you sure you're not getting an error in the console? You need to give the div an `id`.

**Comment by ginolon** [comment]
I confirm that in Rails Console Live Log there is no error.

In Chrome Tools yes, it says to me to put an id.
