### ISSUE TITLE
Turbolinks remote form + Ladda?

### ISSUE THREAD

**Issue by gregblass** [rails/turbolinks#531]
I'm using Ladda for a loader image on my submit button on a remote form:

    <%= f.button :button, class: "btn-success btn-lg ladda-button top-margin", data: {style: "expand-right"} do %>
        Save Changes
    <% end %>

On success, it will redirect to a page using Turbolinks. However, if the user hits back, the button will still be in the loading state. Does anyone have any insight on how I could deal with this?

Edit: More details here: http://stackoverflow.com/questions/30206177/turbolinks-ladda

Edit 2: I'm just not realizing that all of my JS is broken after hitting back. None of my bootstrap stuff works and the JS that I'm using for my mobile flyout menu isn't firing either. Is there maybe a callback for when the user hits the back button? Or, how is JS re-enabled when the back button is pressed?

**Comment by Thibaut** [comment]
Closing this issue as I see you already answered your own question on SO.

Putting your initialization code in a `<script data-turbolinks-eval=always>` is one option. A better one is to put the code in a `page:load` callback:
```js
$(document).on("ready page:load", function() {
  $(".ladda-button").ladda();
  $(".ladda-button").ladda('stop');
  $(".ladda-button").ladda('bind');
});
```
This will get called on every page load + history back/forward.
