### ISSUE TITLE
Some Javascript plugins like jsTree problems on loading with partial replacement

### ISSUE THREAD

**Issue by ginolon** [rails/turbolinks#535]
Like I said in this issue I have problem with jsTree and other js "plugins".

https://github.com/vakata/jstree/issues/1118

I have a standard configuration of Rails 4.2.1. I add in Gemfile the last master release of Turbolinks 3, but things don't work.

What to do?

It seems that there is two time the click.

Also if I put this code (https://github.com/vakata/jstree/issues/1070) in the view or in the **application.js**

It's the same. The first load of the page everything works beautiful, on the first loading in partial replacement the jsTree doesn't work anymore. If I click one time or if I use it like default (double click on tree) it doesn't. If the tree is already opened it on double click (after loading in partial replacement) reopen itself!

**Comment by ginolon** [comment]
Now I've just discovered something:

If i start with first load of the page let's say here:

**localhost/books/**

the jsTree start good and everything works excellent

(Turbolinks 3 partial replacement has not yet been called!)

I click on a node (the links is like this above):

```ruby
<%= link_to "Something", choose_category_path(category.name), remote: true %>
```

and the new page is loaded with Turbolinks 3 partial replacement.

Now the page is like this:

**localhost/books?category=Thriller**

and jsTree is frozen at the same level before the click (the node's levels are opened where I opened them because of partial replacement)

but now I can't click on the node because it don't works.

If I click again on another or the same link of before (the link's structure are the same of the first one) the jsTree came back to works again! MAGICAL! And now it's still Turbolinks 3 Partial replacement! Absurd!

Why this?

I add in application.js this code:

```javascript
var ready;

ready = function() {
    $('#menu').on('click', '.jstree-anchor', function (e) { $(this).jstree(true).toggle_node(this); });
}

$(document).ready(ready);
$(document).on('page:load', ready);
```

Where am I wrong?

**Comment by vizo** [comment]
Try with .on("page:change", ready).

**Comment by ginolon** [comment]
Thanks @vizo for your answer.

Nothing to do. It doesn't work!

**Comment by ginolon** [comment]
Or better, if I use this code it doesn't work because it don't close the tree, it just reopen:

```javascript
var ready;
var change;

ready = function() {
    something
}

change = function() {
  $('#menu').on('click', '.jstree-anchor', function (e) { $(this).jstree(true).toggle_node(this); });
  alert("Change!");
}

$(document).ready(ready);
$(document).on('page:load', ready);
$(document).on('page:change', change);
```

If I change the line:

```javascript
 $('#menu').on('click', '.jstree-anchor', function (e) { $(this).jstree(true).open_node(this); });
```

it works. But I have to close the tree with icon e not with single click on node!

**Comment by vizo** [comment]
How many times alert("Change!")? is triggered? Maybe it's not just once.
In my cases i did:
```javascript
$('#menu').off('click.jstree').on('click.jstree', '.jstree-anchor', function (e) {
  $(this).jstree(true).toggle_node(this);
});
```
This will bind "click" event just once.

**Comment by ginolon** [comment]
Great! It works now!

I still don't know why, but it works!!!!

Can you explain me why?

**Comment by Thibaut** [comment]
This points to issues with the way the `page:load` and `page:change` events fire on partial replacement. We should pass which elements were replaced so that callbacks can skip re-adding state to nodes that weren't replaced. I'll look into this soon.

**Comment by Thibaut** [comment]
https://github.com/rails/turbolinks/pull/537
