### ISSUE TITLE
Cached page restore docs event missing

### ISSUE THREAD

**Issue by amnesia7** [rails/turbolinks#536]
I think the readme needs updating for **Restore a cached page from the client-side cache**.

I think it should also include the `page:after-remove` event as well.

**Comment by Thibaut** [comment]
Do you just mean we should add that to the README?

**Comment by amnesia7** [comment]
Yes. The js seems to fire the event but the readme docs don't mention it in the list of ones that are run when restoring a cached page from the client side cache.

**Comment by Thibaut** [comment]
Fixed
