### ISSUE TITLE
Not working with Bootstrap's dropdown menu

### ISSUE THREAD

**Issue by 19ray** [rails/turbolinks#539]
The menu only works when first time the page is loaded.
When I go to another page, the menu is toggled twice (i.e open and closed immediately).
I discovered that the EventListener is created and duplicated, whenever I navigate to another page.
I have tried to add the **jquery-turbolinks** gem, but it still doesn't work.
P.S I load the javascript file just before `</body>`

My **application.js**
```
//= require jquery
//= require jquery.turbolinks
//= require jquery_ujs
//= require bootstrap
//= require_tree .
//= require turbolinks
```

I'm not using the bootstrap Nav Bar. I just created it manually.
```
<ul id="uiHdrUser" class="pull-right">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">User <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu" style="right: 0; left: auto;">
            <li><a>........</a></li>
            ....
        </ul>
    </li>
</ul>
```

Thanks!

**Comment by reed** [comment]
Add `data-turbolinks-eval=false` to the application.js `<script>` tag and it'll work.  Without it, all your javascript will re-evaluated on every page.

**Comment by 19ray** [comment]
Thanks @reed ! It does work!

**Comment by FiloSpaTeam** [comment]
I don't want to necrobump this but i used this solution to use turbolinks and reload dropdown (inside turbolinks:load event):
```coffeescript
$(document).on "turbolinks:load", ->
  $('.dropdown-toggle').dropdown()
```
