### ISSUE TITLE
Partial replacement issue.

### ISSUE THREAD

**Issue by tombroomfield** [rails/turbolinks#545]
Hi, encountered a strange issue with the partial replacements. ]

I am attempting to change only a single element in a grid, but using the redirect_to :back, change: 'items:31' method. This change causes the height of the element to reduce.

When I do this, the entire app flashes white for an instant, before then rendering the page with distorted elements below it, for instance:
![screen shot 2015-05-29 at 4 39 37 pm](https://cloud.githubusercontent.com/assets/5423793/7877668/5ec0614e-0621-11e5-89ec-cdb780a277ac.png)

Scrolling, or causing it to re-render in any way causes it to return to normal.

**Comment by tombroomfield** [comment]
Okay, more information on this,
The rendering issue occurred because the bottom of the grid had no height set, so expanded to fit the children items. When I changed an element, reducing the height, the overall grid also reduced, but failed to render the lower items correctly. I fixed this by settings the grids height to fill the page.

However, I still get a white flash on replace, which is quite jarring, any idea what is causing this?

Thanks,

**Comment by Thibaut** [comment]
Hard to debug with just a screenshot. Could you link to a live demo? Which browser are you using?

**Comment by tombroomfield** [comment]
Yeah, I understand how limited my information, apologies for that. Unfortunately the app is private/enterprise so a link i s difficult, Ill see if I can throw together an example application just reproducing this issue and link it back.

Thanks,
Tom.

**Comment by Thibaut** [comment]
Feel free to reopen if you can put together an example app.
