### ISSUE TITLE
Window is scrolled to (0, 0) when redirected to the same page with cache enabled

### ISSUE THREAD

**Issue by christophemaximin** [rails/turbolinks#547]
Scenario:
- There is a list of posts with upvoting buttons
- User scrolls down the list of posts
- User clicks on an upvote button `link_to 'upvote', upvote_post_path(post), remote: true, method: :post`
- The upvote action ends up with `redirect_to posts_path, change: dom_id(post)`
- Because the user is redirected to a page that's cached, this: https://github.com/rails/turbolinks/blob/a2b1810a60fea0ea131eea39fae65a771f2938a9/lib/assets/javascripts/turbolinks.js.coffee#L33 will be called without options, and https://github.com/rails/turbolinks/blob/a2b1810a60fea0ea131eea39fae65a771f2938a9/lib/assets/javascripts/turbolinks.js.coffee#L258 will end up being executed.
- The page is scrolled to the top, but we just wanted to change a div and not anything else.

The simple fix that I found is the following: checking whether we're fetching the same page or not to decide on the scrolling: https://github.com/christophemaximin/turbolinks/commit/c6c4e6009b7dd923a5858c872ac0009c5380ffa8

Maybe it would be better to do prevent scrolling only if we're about to change specific nodes on the page.
But with this issue, `Turbolinks.visit(..., change: ... )` is breaking the UX everytime we have a longer page.

I'm not sure my fix 100% correct, and I'm not sure how to test this.
Suggestions ?

**EDIT:** Just discovered this commit https://github.com/rails/turbolinks/commit/5c010563074fad969a7a6199a692fe69759018cf
I'd say my issue is still valid because I can't set the `scroll: false` from the rails controller side... and should it be there anyway ? Automatically preventing the scroll when we're changing an element on the same page looks like a more elegant solution to me.

**Comment by Thibaut** [comment]
Thanks for nicely explaining your issue.

I think the fix here is to not use the transition cache when the `change` option is set. I can't think of a scenario where you'd want that to happen.

```
-  if transitionCacheEnabled and cachedPage = transitionCacheFor(url.absolute)
+  if transitionCacheEnabled and !options.change and cachedPage = transitionCacheFor(url.absolute)
```

Would this work for you?

**Comment by christophemaximin** [comment]
@Thibaut  Your change is much better indeed! I submitted PR #549 related to this.

On the side, I'm curious as to why 

    +  if transitionCacheEnabled and !options.change and cachedPage = transitionCacheFor(url.absolute)

works but 

    +  if transitionCacheEnabled and cachedPage = transitionCacheFor(url.absolute) and !options.change

which I tried before, breaks the `Turbolinks.visit() with transition cache` test ?

**Comment by Thibaut** [comment]
Because 

```
if transitionCacheEnabled and cachedPage = transitionCacheFor(url.absolute) and !options.change
```

is equivalent to:

```
if transitionCacheEnabled and cachedPage = (transitionCacheFor(url.absolute) and !options.change)
```

**Comment by christophemaximin** [comment]
Good catch!
