### ISSUE TITLE
XHR & redirect_to broken after adding turbolinks

### ISSUE THREAD

**Issue by pch** [rails/turbolinks#548]
Hi,

I've run into a problem after adding turbolinks to my app. I have a 2-step form in a modal window that works with XHR requests. You fill in the form, submit it and it displays the second form - all without reloading the page. Everything worked fine but when I added turbolinks to Gemfile, the redirect to the 2nd step is being performed as a regular HTML request - which results in reloading the whole page.

```erb
<%= simple_form_for(@link, remote: request.xhr?) do |f| %>
  <%= f.input :url %>
  <%= f.submit %>
<% end %>
```

Controller:

```ruby
class LinksController < ApplicationController
  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
 
    respond_to do |format|
      if @link.save
        # This redirects to the 2nd step
        format.js { redirect_to new_review_path }
      else
        format.js { render :new }
      end
    end
  end
end
```

Logs:

```
Started POST "/links" for ::1 at 2015-05-30 12:57:36 +0200
Processing by LinksController#create as JS
# ...
Redirected to http://localhost:3000/reviews/new
Completed 200 OK in 505ms (ActiveRecord: 11.0ms)

Started GET "/reviews/new" for ::1 at 2015-05-30 12:59:28 +0200
Processing by ReviewsController#new as HTML # - JS format lost
```

Logs without turbolinks:

```
Started POST "/links" for ::1 at 2015-05-30 13:07:17 +0200
Processing by LinksController#create as JS
# ...
Redirected to http://localhost:3000/reviews/new
Completed 302 Found in 642ms (ActiveRecord: 134.3ms)

Started GET "/reviews/new" for ::1 at 2015-05-30 13:07:18 +0200
Processing by ReviewsController#new as JS
```

The only difference here seems to be that turbolinks responds with 200 OK after redirect_to. Is there a workaround I can use to handle this case? Adding `turbolinks: false` to `redirect_to` doesn't seem to do anything.

**Comment by Thibaut** [comment]
```
simple_form_for(@link, remote: request.xhr?) do |f|
```

why is this not `remote: true`?

**Comment by pch** [comment]
The idea is to support both remote & regular requests (in case JS is disabled).

**Comment by pch** [comment]
The idea is to have the form work both within the modal (xhr) and as a regular html page (in case someone visits the url manually).

**Comment by Thibaut** [comment]
`remote: true` just adds an attribute to the form. It won't break the form when JavaScript is disabled (on the contrary, it leaves the form unchanged for exactly that reason).

Your current implementation doesn't work when JS is disabled, as you're only responding to `js`.

Your `create` action should look like this:

```ruby
def create
  @link = Link.new(link_params)

  if @link.save
    redirect_to new_review_path
  else
    render :new, turbolinks: request.xhr?
  end
end
```

**Comment by pch** [comment]
Sorry, I edited my comment above to better explain what I wanted to achieve. It's not just about having it work with js disabled.

There are other respond_to formats (html) - I just stripped them down from the example code.

**Comment by Thibaut** [comment]
Why don't you want the form to be remote even on a regular HTML page?

If you really want to differentiate between the two, I would use a query param `?modal=1` that you carry over in your redirections, not `request.xhr?` (as this won't be true when Turbolinks makes the request).

**Comment by pch** [comment]
Setting `remote: true` doesn't work either, but I'll try to work around it with an additional param - we'll see how it works. Thanks.

**Comment by Thibaut** [comment]
Yes the request to `/reviews/new` will not be JS / `request.xhr?`, as it's made by Turbolinks (this is intended and we can't change it). So you'd need to do something like this:

```ruby
if params[:modal]
  redirect_to new_review_path(modal: '1')
else
  redirect_to new_review_path
end
```

Closing as this isn't a Turbolinks issue.
