### ISSUE TITLE
How to leave DOM node completely untouched?

### ISSUE THREAD

**Issue by pbhogan** [rails/turbolinks#553]
I did a little experiment trying to keep a media player (JW Player) playing continuously while browsing a site. I put it in a part of the page marked with `data-turbolinks-permanent` and sure enough the player survives page transitions, but it seems to reinitialize on page switch.

Is Turbolinks cloning the node or disconnecting and reconnecting it to the DOM causing the embedded player to think it should reinitialize? Is there a way to leave the DOM node completely untouched?

**Comment by tombroomfield** [comment]
Are you using Jquery tubolinks?

**Comment by pbhogan** [comment]
Yes, I am.

**Comment by qq99** [comment]
@pbhogan 
Yeah I think I've encountered the same thing that you have, but using https://github.com/Shopify/turbograft

Disconnecting the node from the DOM and re-adding it can have affects on:
- full screen API status is cancelled
- playing state
- css transitions/animations are killed

**Comment by Thibaut** [comment]
This is a limitation of the DOM. AFAIK there is no solution. See #511.
