### ISSUE TITLE
Using $(document).on("click") with TurboLinks?

### ISSUE THREAD

**Issue by gregblass** [rails/turbolinks#554]
I've been able to have all my javascript work when pressing back and forward using

    <script data-turbolinks-eval=always>

This works well. However, I just ran into a place in my app where there is ajax happening and divs are getting re-rendered. So I've got:
    
    $(document).on("click", "div#derp", function() {

I do it that way so that when I replace those divs on an ajax success, the click function gets applied to the replaced divs as well.

However, this breaks with turbolinks when using the back button, even with the data-turbolinks-eval=always.

Has anyone ran into this and tackled it successfully?

**Comment by smidwap** [comment]
Hey @gregblass, Turbolinks and the back button should play nicely.

Do you have multiple `<div>`'s with id `#derp`? If so, that could be why the `click` event isn't registering.

Also, where does this javascript code live? In the view wrapped by `<script data-turbolinks-eval=always>` or in the compiled js file?

**Comment by Thibaut** [comment]
Some fixes for the back button just went out in `master` (btw `data-turbolinks-eval=always` isn't available in the latest stable release). If this is still a problem, please open a new issue with a complete example that we can use to reproduce the issue.

**Comment by Thibaut** [comment]
Use this to initialize your plugins:
```js
$(document).on('ready page:load', function(event) {
  $('.foo').bar();
});
```

**Comment by tortuetorche** [comment]
According to [jQuery Turbolinks](https://github.com/kossnocorp/jquery.turbolinks/blob/v2.1.0/README.md#not-working-with-documentonready) it's not recommended to use `$(document).on('ready', function () { /* ... */ });`.
We should use instead `$(document).ready(function)` or `$(function)`.

@Thibaut Can you confirm that?

**Comment by gregblass** [comment]
Thank you Thaibaut. Sorry to keep bugging you, but I'm trying to get my app using the master branch. However, when I run 'gem update turbolinks', nothing happens. I'm specifying the github repository in my gemfile like:

    gem 'turbolinks', git: 'https://github.com/rails/turbolinks.git'

I also tried:

    gem 'turbolinks', git: 'https://github.com/rails/turbolinks.git', branch: 'master'

Still nothing seems to get updated. I was definitely experience back button issues so I wanted to see if the latest changes helped anything.

**Comment by Thibaut** [comment]
@tortuetorche My example was if you don't use `jquery-turbolinks`. If you do, then yes, you should use `$(document).ready(fn)`, as that will automatically bind to the `page:load` event as well.

@gregblass Try `bundle update`.

**Comment by gregblass** [comment]
@Thibaut That worked, thanks!

**Comment by tortuetorche** [comment]
@Thibaut Thank you for the clarification.
