### ISSUE TITLE
Can you fix tag name (v2.5.3)

### ISSUE THREAD

**Issue by yui-knk** [rails/turbolinks#557]
Now tag is named `v.2.5.3`.
I think this would be `v2.5.3` :)

**Comment by Thibaut** [comment]
@rafaelfranca is it ok to delete the existing tag, or just push a new one?

**Comment by rafaelfranca** [comment]
Yeah

**Comment by Thibaut** [comment]
Thanks

**Comment by yui-knk** [comment]
Thanks !!
