### ISSUE TITLE
Turbolinks.visit doesn't trigger page:before-change

### ISSUE THREAD

**Issue by vizo** [rails/turbolinks#561]
Turbolinks.visit doesn't trigger event page:before-change. I want to make confirm, it works on normal links, but if you call Turbolinks.visit directly it doesn't call page:before-change.

Any idea?

**Comment by Thibaut** [comment]
This is intentional but I think it makes sense to also fire the callback on `Turbolinks.visit()`. I'll make the change soon.

**Comment by vizo** [comment]
I think this is already ok. Maybe someone want to do it without triggering.

If you will make the change, it would be nice to know what triggered it. Link or manually by calling Turbolinks.visit(), so you can decide in event function what to do next ...

**Comment by vizo** [comment]
You are right.  page:before-change should always be triggered.
Now i have case form with remote: true and i can't prevent Turbolinks.visit because "page:before-change" is never triggered.

So i made monkey patch at the moment:
```
Turbolinks._visit = Turbolinks.visit.bind();
Turbolinks.visit = function() {
  if ($(document).triggerHandler('page:before-change', arguments) !== false) {
    Turbolinks._visit.apply(this, arguments);
  }
};
```

**Comment by vizo** [comment]
I see it's already done.

**Comment by vizo** [comment]
I think this would also solve https://github.com/rails/turbolinks/issues/586. I think triggering page:before-change must be moved to visit function. There are also known affected elements, so event.data could provide them.

**Comment by Thibaut** [comment]
@vizo sorry I haven't had time to do much work on Turbolinks lately. I'll take care of this within the next two weeks.

**Comment by vizo** [comment]
@Thibaut it's ok, i understand. I made pull request https://github.com/rails/turbolinks/pull/588 If you are interested ...
