### ISSUE TITLE
Stripe external script, long delay after navigating through turbolinks 3

### ISSUE THREAD

**Issue by tehfailsafe** [rails/turbolinks#562]
Everything is working correctly with stripe-rails and using the external `stripe.com` js file, however there is a 10+ second delay when submitting custom form.

If I refresh the page with the form on it works instantly upon submit. If I navigate from another page TO the form page, it has the 10 second delay after submitting.

I'm putting the `<script type="text/javascript" src="https://js.stripe.com/v2/"></script>` in the head, and I have tried all combinations of `data-turbolinks-eval=always`, `data-turbolinks-eval=false` just to see if anything makes a difference... If I disable turbolinks on the page before the form, it works as a hard page load and works perfectly again.

What could be causing this kind of a delay and how can I get around it?

**Comment by Thibaut** [comment]
Could you provide an example app where we can reproduce this?
