### ISSUE TITLE
Turbolinks.replace is great but how can I append new content instead of replacing ?

### ISSUE THREAD

**Issue by naveed-ahmad** [rails/turbolinks#563]
I'm implementing activity feeds functionality in one of my application,  and listing page has infinite page scrolling. 

For now whenever users scroll down I'm loading new feed items and appending them to list. It would be really great if turdbolinks also supports `append`, and  `prepend` methods alongwith `replace` 

So 

`render "partial", append: "feed_items"` will append new items to dom with "feed_item" id
`render "partial", prepend: "feed_items"` will prepend new items to dom with "feed_item" id 

Hopes that make sense.

**Comment by nflorentin** [comment]
+1

**Comment by stephenson** [comment]
That would be fantastic!

**Comment by gildo** [comment]
:+1:

**Comment by Thibaut** [comment]
https://github.com/rails/turbolinks/pull/621
