### ISSUE TITLE
<a href="#accordionOne" data-no-turbolink> doesn't work. The page loads on click.

### ISSUE THREAD

**Issue by ginolon** [rails/turbolinks#565]
I have this:

```html
<div class="panel-heading">
  <h3 class="panel-title"><a data-no-turbolink data-toggle="collapse" data-target="#bodyPanelOne" href="#bodyPanelOne">Title with link</a></h3>
</div>
```

I tried also to put "data-no-turbolink" to a parent div of the link: nothing the same.

If I remove the href="" everything works (the page doesn't loads).

I tried with both Turbolinks 3 (from github) and the older 2.5 (from rubygems).

How to?

**Comment by galulex** [comment]
You should add 'data-no-turbolinks' attribute to any parent element of your link. [Click](https://github.com/rails/turbolinks/blob/master/README.md#opting-out-of-turbolinks)

**Comment by ginolon** [comment]
I tried! nothing! The page loads itself!

**Comment by Thibaut** [comment]
Could you provide an example app where we can reproduce this?
