### ISSUE TITLE
[v2.5.3] A click between a page:restore and page:change restores the wrong page

### ISSUE THREAD

**Issue by elia** [rails/turbolinks#567]
It's a bit tricky to describe but I'll try, feel free to ask for clarification

background:
- slow requests
- transition cache enabled
- start on page at url A

reproduce:
- click on link B
 - fetches B from server

- click on link A
 - restores of A from cache (fires page:change & page:restore)
 - starts fetching of fresh copy of A from server (takes some seconds)

- click on link B (while A is being fetched)
 - triggers the restore from cache lifecycle events but the body isn't updated, the progress bar is activated and reaches 100% (as typical when a page is restored from cache)
 - starts fetching of fresh copy of B from server (takes some seconds)
 - eventually the fresh copy of B arrives and is loaded

**Comment by elia** [comment]
I managed to fix it by storing the raw `url.absolute => xhr.responseText` in a separate cache for transition-cache instead of using the history cache. Then the restore process uses `createDocument` on the stored raw html and repeats the extraction of title & body as it does when the contents come from xhr.

I'd send a PR but would need a v2 branch to target first (#572). 

The change is available here anyway: https://github.com/elia/turbolinks/compare/2-stable...elia:fix-transition-cache

**Comment by Thibaut** [comment]
Is this still an issue in Turbolinks 3 / `master`?

**Comment by elia** [comment]
Alas we had to drop Turbolinks support in our app (we have too many third party ad/tracking JavaScript that we haven't control over and are not PJAX-friendly). 

Not sure if I'll be able to upgrade, re-enable and test in a timely manner. Feel free to close if it should be fixed on master.

**Comment by Thibaut** [comment]
I'll close then. Sorry for the late reply.
