### ISSUE TITLE
Does turbolinks 3 replace works only with remote: true?

### ISSUE THREAD

**Issue by carlesso** [rails/turbolinks#569]
Hi Guys,

I was testing `replace` feature using turbolinks from the master branch and I wasn't able to have partial replacement to work until I made a couple of test. I've created a simple 4.2.3 rails app with this single controller:

```ruby
class WelcomeController < ApplicationController
  def index
    @xhr = request.xhr?
    render :index, change: 'variable'
  end
end
```

and the index page is this:

```html
<div id="static">
  This should not change: <%= rand 1_000_000 %>
</div>

<div id="variable">
  While this should change: <%= rand 1_000_000 %> <br/>

  <% if @xhr %>
    <strong>Request is XHR</strong>
  <% else %>
    <strong>Request is NOT XHR</strong>
  <% end %>
</div>

<%= link_to 'Visit root URL with turbolink', root_url %>
<%= link_to 'Visit root using remote: true', root_url, remote: true %>
<%= link_to "Visit root triggering Turbolinks.visit('/', {change: 'variable'}", root_url, id: 'trigger_visit' %>
```

You *should* be able to see a demonstration [here](https://turbolinks-test-carlesso.c9.io/).

I was trying to figure out if the request has to be an `xhr?` request to work because I was looking at [redirection.rb](https://github.com/rails/turbolinks/blob/master/lib/turbolinks/redirection.rb#L18-L29) and I figured out that Turbolinks requests are not `xhr?`

I my test I figured out that the link with remote: true is an `xhr` request and the body of the response will have the `Turbolinks.replace` function call, while if I user `Turbolinks.visit` the regular response is given in the request and Turbolinks handles the replacement.

So, in the end, my question is: Is Turbolinks remote replacement supposed to work only with `remote: true`? If so, maybe that should be explained a little bit more in the Readme file.

**Comment by Thibaut** [comment]
> Is Turbolinks remote replacement supposed to work only with `remote: true`?

Yes, at the moment server-side partial replacement can only be used with jQuery or another JavaScript library that sends `X-Requested-With: XMLHttpRequest` and evaluates JS responses — not using Turbolinks itself.

You can also do it manually client-side using the `change` option of `Turbolinks.visit/replace`, and we might add partial replacement capabilities to links in the future (with data attributes).

Updated the README: https://github.com/rails/turbolinks#partial-replacement-30
