### ISSUE TITLE
Bug: redirect_to redirecting via HTTP instead of HTTPS

### ISSUE THREAD

**Issue by itay-grudev** [rails/turbolinks#570]
```redirect_to url, turbolink: true```

Redirects via ```HTTP``` instead of ```HTTPS``` on an ```HTTPS``` website which causes the following problem:

The browser rejects the ```HTTP``` request with the following error:

```
Mixed Content: The page at 'https://example.com/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://example.com/'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by Thibaut** [comment]
Fixed by 9d0e8f0a464142901b298eec11ad8d7a768a2c8b.

**Comment by marcamillion** [comment]
The weird thing is that I am experiencing this same issue with Turbolinks 5.0.1 in a Rails 5.0.1 app.

Shouldn't this fix be applied there, if it indeed fixed it?

**Comment by itay-grudev** [comment]
Tubolinks 5 is in another project. See [turbolinks/turbolinks](https://github.com/turbolinks/turbolinks).
