### ISSUE TITLE
Turbolinks partial replace without layout

### ISSUE THREAD

**Issue by galulex** [rails/turbolinks#571]
```slim
body
  #main data-turbolinks-temporary
    .content ' My content goes here
```

```js
  Turbolinks.replace('New content', { change: ['main']})
```

`replace` returns `true` but nothing happens

the next javascript

```js
Turbolinks.replace('<div id="main" data-turbolinks-temporary>New content</div>', { change: ['main']})
```

does the replace but the next error rises: `Uncaught TypeError: Cannot read property 'replaceChild' of null`

on [this line](https://github.com/rails/turbolinks/blob/master/lib/assets/javascripts/turbolinks.js.coffee#L191)

Does somebody know the rules of partial replacement?

**Comment by tortuetorche** [comment]
I think your first call of `Turbolinks.replace()` removes the `<div id="main"></div>` node and replaces it with `New content` text. So your second `Turbolinks.replace()` call can't find the `main` node because it doesn't exist anymore.

**Comment by galulex** [comment]
@tortuetorche I am running this command separately

**Comment by tortuetorche** [comment]
My bad.

For the first call I think it's the expected behaviour, you need to replace the `<div id="main"></div>` node by another `main` id node.

If the original `<div id="main"></div>` node hasn't  a `data-turbolinks-temporary` attribute, your second `Turbolinks.replace()` call will work. So It's a bug related to `data-turbolinks-temporary` attribute.

**Comment by galulex** [comment]
@tortuetorche Thank you. I have removed the `data-turbolinks-temporary` attribute and it works.
But i don't think that it is correct behavior. For instance:

simple rails action:

```ruby
def show
  render :show, change: 'main', layout: !!request.xhr?
end
``` 

will generate the next js: `Turbolinks.replace('show template', { change: ['main']})`. And it will not work because the show template should be wrapped in div with id 'main'

**Comment by tortuetorche** [comment]
If your `main` node is in the layout, I think it's the correct behavior.
Otherwise, if it's in your `show` view, you're right it's not the correct behavior.

**Comment by galulex** [comment]
@tortuetorche Thank you for your help. Closing the issue
