### ISSUE TITLE
Anchors navigation broken in firefox 38.0.5+

### ISSUE THREAD

**Issue by dsulli99** [rails/turbolinks#573]
Hi,

If I disable Turbolinks the expected behavior below is exhibited.  I can only reproduce this in Firefox (it does not present itself in Chrome).

**Steps to reproduce:**

1) Start on some page, i.e. /main
2) Click to link with an anchor in it, i.e. /glossary#somenamedanchor.  This works and navigates to the correct anchor.
3) Click the back button.  The browser history now reflects /glossary (without the hashbang anchor) and navigates to the top of the same page.
4) Click the back button again.  The browser history reflects 1) and is at the original starting position.

**Expected behavior:**

1)  When clicking back on 3), the the browser should navigate to 1).

Implementing data-no-turbolink on the link in 2) fixes this problem.  Also completely disabling turbolinks fixes this problem.

I am using turbolinks 2.5.3 and rails 4.2.0.

Dan

**Comment by Thibaut** [comment]
Sorry for the late reply. This should be fixed in Turbolinks 3 (`master`). Could you try it?

**Comment by dsulli99** [comment]
Sorry for the delay will test and report back soon.

**Comment by dsulli99** [comment]
I believe this issue to be resolved.  Thank you for your help.  Closing this issue.
