### ISSUE TITLE
Cookies fetched/stored incorrectly when path is specified

### ISSUE THREAD

**Issue by pratik60** [rails/turbolinks#574]
Hey

We have recently updated to turbolinks but had to revert back.

The problem is we stories cookies on our site with the same name by specifying the path. So colPreference is stored on accounts page with /accounts as a path, and on campaigns page colPreference is stored with /campaigns as a path. So when we fetch cookie we just look up the cookie with colPreference and that works as it always picks the one most apt (basically with the right path).

I am not sure what's happening after turbolinks integration - Is it storing the cookie with the right path, or fetching it incorrectly.

Any help on how to get around this?

P.S - I'm also using jquery turbolinks.

**Comment by Shoroh** [comment]
I have the same issue. 

I'm using the Bootstrap Tables with cookie extension, and it stores cookies wrong way in everywhere in application:

<img width="532" alt="screen shot 2015-09-04 at 10 48 19" src="https://cloud.githubusercontent.com/assets/1865984/9676212/893bcb2a-52f2-11e5-831b-991b1291328d.png">

But it should be only one path: /administrator/users

Without turbolinks it works well. Any idea?

**Comment by jeremy** [comment]
@Shoroh are you resetting `cookiePath` on `page:update`? https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/cookie#cookiepath

**Comment by Shoroh** [comment]
Oops, I didn't. Thanks!
