### ISSUE TITLE
Turbolinks issue with doubleclick floodlights

### ISSUE THREAD

**Issue by c0m3tx** [rails/turbolinks#577]
Hi,
I have a website which uses many doubleclick floodlights.

With Turbolinks enabled when I navigate to a page which uses floodlight i end up with a blank page.

If I look at the code, looks like the "document.write" in the floodlight replaces the whole page, while normally it should only append a iframe to the DOM structure.

Is there anything we can do to make it work? Something to replace in the floodlight?

**Comment by Thibaut** [comment]
This sounds like an issue with floodlights. Please post code / reproducible steps or close this issue.
