### ISSUE TITLE
Sprockets::FileNotFound at / couldn't find file 'turbolinks' with type 'application/javascript'

### ISSUE THREAD

**Issue by gregblass** [rails/turbolinks#578]
I just updated the gem to master and I'm getting this error when I start my server:

    Sprockets::FileNotFound at / couldn't find file 'turbolinks' with type 'application/javascript'

Is there some type of configuration change I need to make to use the latest version?

**Comment by gregblass** [comment]
Nevermind. This can be deleted. False alarm.

**Comment by jklon** [comment]
Hello
I am getting the same problem. What is the solution?

**Comment by gregblass** [comment]
@jklon I can't remember, but for what its worth, you should be using Turbolinks 5. Its much more refined!

**Comment by Argonus** [comment]
@gregblass, @jklon  Hi, i also have this issue, i try to add turbolinks 5. Do you remember what was solution?

**Comment by amitpatelx** [comment]
I am facing the same issue with trubolinks5 in production. How can I fix that?
