### ISSUE TITLE
Polymer and Turbolinks doesn't load content

### ISSUE THREAD

**Issue by nonameolsson** [rails/turbolinks#580]
https://www.youtube.com/watch?v=Zqtn9uxI1xs

It seems like Polymer elements aren't loaded after changing page with Turbolinks. Has this something to do with how Turbolinks works?

**Comment by Thibaut** [comment]
Please post code or a URL where we can reproduce / investigate.

**Comment by abitdodgy** [comment]
@nonameolsson sorry, off topic, but what packages are you using to get Polymer working with Rails?
