### ISSUE TITLE
Display Progress Bar only if loading time exceeds 4 seconds.

### ISSUE THREAD

**Issue by ginolon** [rails/turbolinks#581]
I need to visualize the progress bar only if the time exceeds 4 seconds.

How can I do?

**Comment by Thibaut** [comment]
@javan should we provide an option for delaying the progress bar by n milliseconds?

**Comment by ginolon** [comment]
Yes, please.

**Comment by javan** [comment]
Yes, we were just talking about this recently. And I think we should set a default of ~300-500ms because the progress bar actually makes loading feel _slower_ for fast requests. Assigned myself to this one.

**Comment by javan** [comment]
Done https://github.com/rails/turbolinks/pull/608
