### ISSUE TITLE
redirect_to and scroll to acnhor

### ISSUE THREAD

**Issue by vizo** [rails/turbolinks#589]
When using redirect_to with anchor, change and scroll:true, it doesn't scroll to anchor.

I checked source code and i see that scroll param is never passed from server to client side.
I fixed this also in pull request https://github.com/rails/turbolinks/pull/588.

**Comment by Thibaut** [comment]
Could you provide a test app for reproducing this?
I don't think the solution is to expose the `scroll` option server-side.

**Comment by vizo** [comment]
Use case is when you update some resource "inline" (single page).
For example you have list of items with edit button you do turbolinks.visit to edit (to show form) and after save you redirect_to with anchor, but without scroll true it doesn't scroll to anchor (to saved item).

**Comment by Thibaut** [comment]
The fix isn't to expose `scroll` server-side. We should make `Turbolinks.visit` with `change` scroll to the URL fragment by default, instead of leaving the scroll position unchanged.

I will take care of this in the coming weeks.

**Comment by vizo** [comment]
Yes i agree, this solution is better. Thanks :)
