### ISSUE TITLE
page:partial-load without jQuery

### ISSUE THREAD

**Issue by cchko** [rails/turbolinks#595]
Is there a way to bind to the `page:partial-load` event without jQuery? Couldn't find documentation for this.

**Comment by tortuetorche** [comment]
From the [turbolinks_replace_test.coffee](https://github.com/rails/turbolinks/blob/25f07dd9c12f7ecef0a01138d1430afeb94c9f2d/test/javascript/turbolinks_replace_test.coffee#L42) file, I guess:
```coffee
 document.addEventListener 'page:partial-load', (event) ->
      # your code here
```
Or in javascript:
```javascript
document.addEventListener('page:partial-load', function(event) {
  // your code here
});
```

**Comment by Thibaut** [comment]
:+1:

**Comment by cchko** [comment]
Thanks!
