### ISSUE TITLE
Progressbar enable documentation wrong

### ISSUE THREAD

**Issue by johannesluedke** [rails/turbolinks#598]
The documentation states to use
    Turbolinks.ProgressBar.enable();
but doesn't work for me.
What works is:
    Turbolinks.enableProgressBar();

Rails 4.0.13, turbolinks 2.5.3, Foundation & JQuery

**Comment by Thibaut** [comment]
The documentation in `master` is for Turbolinks 3.
See https://github.com/rails/turbolinks/tree/2-5-stable for the latest stable release.
