### ISSUE TITLE
How to load `turbolinks` in an engine

### ISSUE THREAD

**Issue by sebastianzillessen** [rails/turbolinks#605]
Hi,

at my current project, we have a large software that is wrapped in a private gem. This is included in all customer projects to be able to have a default project which can be extended and to provide all users with the latest version. 

Now I would like to include the `turbolinks` javascript files into that engine. 
Therefore I did the following: 
- gem as dependency in the Gemspec (`s.add_dependency 'turbolinks' `) 
- added the line into the application.js (`//= require turbolinks`)
- `bundle install` in the main project (I can see that `turbolinks` gets installed: `Using turbolinks 2.5.3`)

But when I try to reload the page (after server restart) I get the following error:

````
Sprockets::FileNotFound at /<something>
couldn't find file 'turbolinks'
  (in /Users/sebastianzillessen/<project>/<gem-engine>/app/assets/javascripts/application.js:15)
````

Any ideas, what I'm doing wrong?

Thank you!

**Comment by Thibaut** [comment]
Try to add `require 'turbolinks'` in your gem's main file.

**Comment by sebastianzillessen** [comment]
Yeah that did it
