### ISSUE TITLE
page:before-change not triggered on page restore

### ISSUE THREAD

**Issue by itay-grudev** [rails/turbolinks#609]
According to your documentation the `page:before-change` event should be triggered when restoring a page (going back for example), but that is not the case.

**Comment by Thibaut** [comment]
This is intended, because `popstate` events are not preventable (unlike normal visits). Also, when the `popstate` event fires, the URL has already changed, so firing `page:before-change` at that time would lead to inconsistent behavior.

What are you using the event for?

**Comment by itay-grudev** [comment]
I needed to update something if the user goes back. Please create an event that is invoked in both cases, and explicitly note that it can't be prevented.

**Comment by Thibaut** [comment]
Have you tried using `page:before-unload`? It fires before the page changes (including on partial replacement).

**Comment by itay-grudev** [comment]
I tried many solutions and I ultimately gave up. I did tried `before-unload`, but as far as I remember it wasn't invoked on going back or it reported wrong URL. I don't really remember, but it didn't do the job.

**Comment by Thibaut** [comment]
It is invoked on history back/forward. What URL did you expect it to report? How are you reading the URL?

**Comment by itay-grudev** [comment]
I ultimately used a variable to store the previous page loaded and I bypassed the problem. Thank you for your time and will to help, but this was a month ago and I really don't remember.
