### ISSUE TITLE
What is the Turbolinks roadmap?

### ISSUE THREAD

**Issue by tortuetorche** [rails/turbolinks#612]
Hi folks,

> 3) Ground-up rewrite of Turbolinks (v5) for performance & extensibility. Unreleased, but you can follow along here: https://github.com/basecamp/turbolinks/tree/v5/lib/assets/javascripts/turbolinks
> -- <cite>@sstephenson</cite> (https://twitter.com/sstephenson/status/645993147399405568)

So v5 will be the next major release of Turbolinks.
But what will be the backwards-incompatible changes of this fifth release?
Is the `Turbolinks.replace()` will be kept?

Thanks in advance,
Tortue Torche

**Comment by rafaelfranca** [comment]
It is hard to know. The announcement was made yesterday and only Basecamp people have context about it. That said you can ask this question in their repository.

**Comment by sstephenson** [comment]
There's no roadmap right now. Turbolinks 5 is still an R&D project here at Basecamp. Continue using the current version, and we'll make sure there's a migration path everyone's happy with when the time comes.
