### ISSUE TITLE
Does 'partial-load' really get `changedNodes`?

### ISSUE THREAD

**Issue by metaskills** [rails/turbolinks#613]
When writing events handlers like this for `partial-load`:

```javascript
$(document).on('page:partial-load', function(changedNodes) {
  // ...
});
```

I am finding that the `changedNodes` argument is actually a jQuery event. I could not find an interface to to talk to these like document fragments or what I can do with these? Are these supposed to be jQuery event objects?

**Comment by Thibaut** [comment]
The changed nodes are in `event.data`.

**Comment by metaskills** [comment]
I thought about looking there... but did not see it? Thanks in advance for the help!

![screen shot 2015-09-24 at 1 56 47 pm](https://cloud.githubusercontent.com/assets/2381/10081692/242cb41a-62c4-11e5-95e3-a01866652222.png)

**Comment by Thibaut** [comment]
Hmm that's weird. Is there anything in `event.originalEvent.data`?

**Comment by metaskills** [comment]
Bingo!

![screen shot 2015-09-24 at 1 58 19 pm](https://cloud.githubusercontent.com/assets/2381/10081720/550e04f8-62c4-11e5-9a04-b95decc964cc.png)

**Comment by Thibaut** [comment]
Too bad jQuery doesn't make the DOM event's data available on its custom event object…

I'll close this when I update the docs to mention that.

**Comment by metaskills** [comment]
Thanks!!!
