### ISSUE TITLE
Replace doesn't do anything, what am I doing wrong?

### ISSUE THREAD

**Issue by firedev** [rails/turbolinks#614]
I have html that looks correct to me:
```html
<div id="id" data-turbolinks-temporary>Replace this<div>
```
No errors in console:
```javascript
$('#id')
[<div id=​"id" data-turbolinks-temporary>​…​</div>​]

$('[data-turbolinks-temporary]')
[<div id=​"id" data-turbolinks-temporary>​…​</div>​]

Turbolinks.replace('hello', {change: ['id']})
true
```
But nothing changes:
```javascript
$('#id').text()
"Replace this"
```

**Comment by tortuetorche** [comment]
Hi @firedev,

Can you try this ?
```javascript
Turbolinks.replace('<div id=​"id" data-turbolinks-temporary>hello</div>', {change: ['id']});
```

Cheers,
Tortue Torche

**Comment by firedev** [comment]
Okay I see now. 

But still, I need to replace `<td>` and it works only with `<div>`. Is it by design?

**Comment by tortuetorche** [comment]
For replacing a `<td>`, you can do that:

```javascript
Turbolinks.replace('<table><tr><td id=​"id" data-turbolinks-temporary>hello</td></tr></table>', {change: ['id']});
```

**Comment by firedev** [comment]
Thanks I'll try in the morning. But this means I need to add another view around my `td` just to render it from Turbolinks.

Kind of defeats the purpose.

**Comment by tortuetorche** [comment]
I don't think that replacing the content with an HTML fragment is the main goal of `Turbolinks.replace()`.
You should have an entire HTML page in the first argument of `Turbolinks.replace()`, not a fragment of it.

**Comment by firedev** [comment]
In fact I am rendering this from the controller. And yes I am replacing `js.erb` partial with `render change`. But it happens that I can render only part of the view.
