### ISSUE TITLE
3.0 release date

### ISSUE THREAD

**Issue by jacekgrzybowski** [rails/turbolinks#623]
Are there plans to release `3.0` gem before Rails 5 is out?

I'm currently using latest master (it fixes major `popState` issues and works properly with backbone router), but would feel much safer using an officially released `3.x` gem.

**Comment by kaspth** [comment]
Not as far as I know.

Do send pull requests if you find any issues with master. Otherwise 3.0 could be a lipstick on a pig release. Then the theoretical safety is out the sty :grin:
