### ISSUE TITLE
Turbolink redirects behind nginx proxy

### ISSUE THREAD

**Issue by vevisystems** [rails/turbolinks#625]
Hi,

We have a rails application with turbolinks enabled, behind a reverse nginx proxy which also rewrites the url (actually it adds an extra folder to the request path). That is, a request to:

http://www.example.com/whatever

gets changed into

http://www.example.com/extra/whatever

before sending it to the upstream rails server.

With regular redirects, this works pretty well thanks to nginx proxy_redirect directive. 
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect

However, turbolinks adds a "non-standard" X-XHR-Redirected-To header, making the extra path go to the client and producing an invalid request from the browser. 

How you deal with this kind of issues? Is there any solution available? I would prefer not having to disable turbolinks, as speed boost is quite impressive.

**Comment by Thibaut** [comment]
Turbolinks needs the `X-XHR-Redirected-To` header to update the URL in the location bar when the server performs a redirection. Without it it would use the wrong URL (the one before the redirection).

Closing the issue since this is not a Turbolinks bug. I'd recommend asking on StackOverflow.

**Comment by vevisystems** [comment]
While I agree it may be not a turbolink bug, it is really a problem as inverse proxies are very common in any web architecture, so in my opinion turbolinks should support it. Anyway, I will try to find a solution and suggest it here if I found one.

**Comment by quentindemetz** [comment]
@vevisystems any luck?

**Comment by vevisystems** [comment]
Not really, we had to change our implementation to avoid this problem. I don't actually remember what we needed to do, but in any case it was not a solution to this problem.
