### ISSUE TITLE
Turbolinks 3 Partial replacement not working

### ISSUE THREAD

**Issue by devmarwen** [rails/turbolinks#633]
I have this `create` `action` for a `remote` `form`

```ruby
def create
  if @record.save
    redirect_to @record
  else
    render :new, change: "new_record"
  end
end
```
Here when the saving succeed, the redirect happens successfully using **Turbolinks** and I can see `Turbolinks.visit('the_actual_url');` in the network panel.
But when the saving fails, "nothing" happens, the `response` in the network panel is the rendered HTML page including the `form` with its errors. Somehow **Turbolinks** is not taking charge of the `rendering`

**Comment by Thibaut** [comment]
Are you using Turbolinks master in your Gemfile? The new version hasn't been released yet.

**Comment by devmarwen** [comment]
Yes. I'm using the master branch

**Comment by devmarwen** [comment]
It's Coming from the **jbuilder 2.3.2** Gem. I removed it and **Turbolinks** works again like expected!
